CD: #各种操作cd 必须为整数 单位：分
  association: 10080 #宗门维护
  joinassociation: 20 #退宗
  associationbattle: 1440 #宗门大战
  rob: 30 # 打劫CD
  gambling: 1 # 金银坊
  couple: 30 #双修
  caibu:  30 #采补
  garden: 3 # 药园
  level_up: 0 # 突破
  secretplace: 1 #秘境
  timeplace: 1 #仙府
  forbiddenarea: 1 #禁地
  reborn: 0.1 # 重生
  transfer: 30 # 转账
  honbao: 1 # 抢红包
  boss: 30 #boss
  bossSpawn: 4320 #boss刷新
  xijie: 10 #洗劫

percentage:
  cost: 0.05 #手续费
  Moneynumber: 1 #金银坊收益
  punishment: 0.5 #出千收益

size:
  Money: 100 #单位：万，出千控制
mine: #挖矿最长时间：最低*周期
  size: 100 #闭关倍率！收益：倍率*境界数*天赋*时间
  time: 30 #闭关最低时间
  cycle: 24 #闭关周期
switch: #开true 关false
  play: true #怡红院开关
  Moneynumber: true #金银坊开关
  couple: true #双修开关
  Xiuianplay_key: true #怡红院卡图开关

biguan: #闭关最长时间：最低*周期
  size: 7 #闭关倍率！收益：倍率*境界数*天赋*时间
  time: 30 #闭关最低时间
  cycle: 240 #闭关周期

work: #打工
  size: 150 #打工倍率！收益：倍率*境界数*时间
  time: 15 #打工最低时间
  cycle: 48 #打工周期

Boss:
  Boss: 12 #奖励倍率

Auction:
  interval: 2 #间歇时间
  openHour: 20 #星阁开启时间
  closeHour: 21 #星阁关闭时间

SecretPlace: #秘境出金概率
  one: 0.99 #0.9保底，0.1蚂蚁
  two: 0.6
  three: 0.35 #0.35出金，0.65小金

najie_num: # 纳戒存储量
  - 50000
  - 100000
  - 200000
  - 500000
  - 1000000
  - 2000000
  - 5000000

najie_price: # 纳戒升级消耗 需要对应najie_num保持数据量一致
  - 0
  - 5000
  - 10000
  - 50000
  - 50000
  - 100000
  - 300000

Group: #推送群
  - 1111